GCC_VERSION      := $(shell $(CONFIG_SHELL) $(PWD)/scripts/gcc-version.sh $(CROSS_COMPILE)gcc)
ccflags-y += -Idrivers/media/video/msm8x60
ccflags-y += -Idrivers/media/video/msm8x60/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o

